name: Update Shield
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update Shielded.dev Badge
        uses: shieldeddotdev/shielded-action@v1
        with:
          shielded-token: ${{ secrets.SHIELDED_TOKEN }}
          title: 'Title of the badge'
          color: '0011aa'
          text: '0 warnings'
