name: Update Shield
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "builddate=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
        id: date

      - name: Update Shielded.dev Badge
        uses: shieldeddotdev/shielded-action@v1
        with:
          shielded-token: ${{ secrets.SHIELDED_TOKEN }}
          text: ${{ steps.date.outputs.builddate }}
