on: [push, pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Install Node
        uses: actions/setup-node@v6

      - name: Install Dependencies
        run: make deps

      - name: Lint
        run: make lint

      - name: Build
        run: make clean release

      - name: Test
        run: go test ./...
